using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Onderzoek_Bussimulatie
{
    class FixedDistribution
    {
        // Returns distribution of people
        public static int[] GetDistribution(double peaks, int peakHeight, int finalPeak)
        {
            int[] distribution = relevantPeak((int)peaks, peakHeight, finalPeak);
            return distribution;
        }

        // Select 
        public static int[] relevantPeak(int peaks, int peakHeight, int finalPeak)
        {
            int[] distribution = new int[60];
            switch (peaks)
            {
                case 1:
                    distribution[0] = peakHeight;
                    break;
                case 2:
                    distribution[0] = peakHeight;
                    distribution[30] = finalPeak;
                    break;
                case 3:
                    distribution[0] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[40] = finalPeak;
                    break;
                case 4:
                    distribution[0] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[45] = finalPeak;
                    break;
                case 5:
                    distribution[0] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[24] = peakHeight;
                    distribution[36] = peakHeight;
                    distribution[48] = finalPeak;
                    break;
                case 6:
                    distribution[0] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[50] = finalPeak;
                    break;
                case 7:
                    distribution[0] = peakHeight;
                    distribution[9] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[26] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[43] = peakHeight;
                    distribution[51] = finalPeak;
                    break;
                case 8:
                    distribution[0] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[38] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[53] = finalPeak;
                    break;
                case 9:
                    distribution[0] = peakHeight;
                    distribution[7] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[27] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[47] = peakHeight;
                    distribution[54] = finalPeak;
                    break;
                case 10:
                    distribution[0] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[18] = peakHeight;
                    distribution[24] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[36] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[54] = finalPeak;
                    break;
                case 11:
                    distribution[0] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[11] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[22] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[33] = peakHeight;
                    distribution[39] = peakHeight;
                    distribution[44] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[55] = finalPeak;
                    break;
                case 12:
                    distribution[0] = peakHeight;
                    distribution[5] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[55] = finalPeak;
                    break;
                case 13:
                    distribution[0] = peakHeight;
                    distribution[5] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[19] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[37] = peakHeight;
                    distribution[41] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[55] = finalPeak;
                    break;
                case 14:
                    distribution[0] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[13] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[21] = peakHeight;
                    distribution[26] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[39] = peakHeight;
                    distribution[43] = peakHeight;
                    distribution[47] = peakHeight;
                    distribution[52] = peakHeight;
                    distribution[56] = finalPeak;
                    break;
                case 15:
                    distribution[0] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[16] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[24] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[36] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[44] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[52] = peakHeight;
                    distribution[56] = finalPeak;
                    break;
                case 16:
                    distribution[0] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[19] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[27] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[38] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[49] = peakHeight;
                    distribution[53] = peakHeight;
                    distribution[57] = finalPeak;
                    break;
                case 17:
                    distribution[0] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[7] = peakHeight;
                    distribution[11] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[18] = peakHeight;
                    distribution[21] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[39] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[49] = peakHeight;
                    distribution[53] = peakHeight;
                    distribution[56] = finalPeak;
                    break;
                case 18:
                    distribution[0] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[7] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[24] = peakHeight;
                    distribution[27] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[37] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[44] = peakHeight;
                    distribution[47] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[54] = peakHeight;
                    distribution[57] = finalPeak;
                    break;
                case 19:
                    distribution[0] = peakHeight;
                    distribution[3] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[9] = peakHeight;
                    distribution[13] = peakHeight;
                    distribution[16] = peakHeight;
                    distribution[19] = peakHeight;
                    distribution[22] = peakHeight;
                    distribution[26] = peakHeight;
                    distribution[29] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[39] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[52] = peakHeight;
                    distribution[55] = peakHeight;
                    distribution[58] = finalPeak;
                    break;
                case 20:
                    distribution[0] = peakHeight;
                    distribution[3] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[9] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[18] = peakHeight;
                    distribution[21] = peakHeight;
                    distribution[24] = peakHeight;
                    distribution[27] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[33] = peakHeight;
                    distribution[36] = peakHeight;
                    distribution[39] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[51] = peakHeight;
                    distribution[54] = peakHeight;
                    distribution[57] = finalPeak;
                    break;
                case 21:
                    distribution[0] = peakHeight;
                    distribution[3] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[9] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[26] = peakHeight;
                    distribution[29] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[37] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[43] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[49] = peakHeight;
                    distribution[51] = peakHeight;
                    distribution[54] = peakHeight;
                    distribution[57] = finalPeak;
                    break;
                case 22:
                    distribution[0] = peakHeight;
                    distribution[3] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[9] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[26] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[31] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[37] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[51] = peakHeight;
                    distribution[54] = peakHeight;
                    distribution[56] = peakHeight;
                    distribution[59] = finalPeak;
                    break;
                case 23:
                    distribution[0] = peakHeight;
                    distribution[3] = peakHeight;
                    distribution[5] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[13] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[18] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[33] = peakHeight;
                    distribution[36] = peakHeight;
                    distribution[38] = peakHeight;
                    distribution[41] = peakHeight;
                    distribution[43] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[51] = peakHeight;
                    distribution[53] = peakHeight;
                    distribution[56] = finalPeak;
                    break;
                case 24:
                    distribution[0] = peakHeight;
                    distribution[3] = peakHeight;
                    distribution[5] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[13] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[18] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[33] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[38] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[43] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[53] = peakHeight;
                    distribution[55] = peakHeight;
                    distribution[58] = finalPeak;
                    break;
                case 25:
                    distribution[0] = peakHeight;
                    distribution[3] = peakHeight;
                    distribution[5] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[22] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[27] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[37] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[47] = peakHeight;
                    distribution[49] = peakHeight;
                    distribution[52] = peakHeight;
                    distribution[54] = peakHeight;
                    distribution[57] = peakHeight;
                    distribution[59] = finalPeak;
                    break;
                case 26:
                    distribution[0] = peakHeight;
                    distribution[2] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[7] = peakHeight;
                    distribution[9] = peakHeight;
                    distribution[11] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[16] = peakHeight;
                    distribution[18] = peakHeight;
                    distribution[21] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[37] = peakHeight;
                    distribution[39] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[44] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[49] = peakHeight;
                    distribution[51] = peakHeight;
                    distribution[53] = peakHeight;
                    distribution[56] = peakHeight;
                    distribution[58] = finalPeak;
                    break;
                case 27:
                    distribution[0] = peakHeight;
                    distribution[2] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[11] = peakHeight;
                    distribution[13] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[19] = peakHeight;
                    distribution[22] = peakHeight;
                    distribution[24] = peakHeight;
                    distribution[26] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[31] = peakHeight;
                    distribution[33] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[37] = peakHeight;
                    distribution[39] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[44] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[53] = peakHeight;
                    distribution[55] = peakHeight;
                    distribution[57] = finalPeak;
                    break;
                case 28:
                    distribution[0] = peakHeight;
                    distribution[2] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[13] = peakHeight;
                    distribution[15] = peakHeight;
                    distribution[17] = peakHeight;
                    distribution[19] = peakHeight;
                    distribution[21] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[36] = peakHeight;
                    distribution[38] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[43] = peakHeight;
                    distribution[45] = peakHeight;
                    distribution[47] = peakHeight;
                    distribution[49] = peakHeight;
                    distribution[51] = peakHeight;
                    distribution[53] = peakHeight;
                    distribution[55] = peakHeight;
                    distribution[58] = finalPeak;
                    break;
                case 29:
                    distribution[0] = peakHeight;
                    distribution[2] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[16] = peakHeight;
                    distribution[19] = peakHeight;
                    distribution[21] = peakHeight;
                    distribution[23] = peakHeight;
                    distribution[25] = peakHeight;
                    distribution[27] = peakHeight;
                    distribution[29] = peakHeight;
                    distribution[31] = peakHeight;
                    distribution[33] = peakHeight;
                    distribution[35] = peakHeight;
                    distribution[38] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[44] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[52] = peakHeight;
                    distribution[54] = peakHeight;
                    distribution[56] = peakHeight;
                    distribution[58] = finalPeak;
                    break;
                case 30:
                    distribution[0] = peakHeight;
                    distribution[2] = peakHeight;
                    distribution[4] = peakHeight;
                    distribution[6] = peakHeight;
                    distribution[8] = peakHeight;
                    distribution[10] = peakHeight;
                    distribution[12] = peakHeight;
                    distribution[14] = peakHeight;
                    distribution[16] = peakHeight;
                    distribution[18] = peakHeight;
                    distribution[20] = peakHeight;
                    distribution[22] = peakHeight;
                    distribution[24] = peakHeight;
                    distribution[26] = peakHeight;
                    distribution[28] = peakHeight;
                    distribution[30] = peakHeight;
                    distribution[32] = peakHeight;
                    distribution[34] = peakHeight;
                    distribution[36] = peakHeight;
                    distribution[38] = peakHeight;
                    distribution[40] = peakHeight;
                    distribution[42] = peakHeight;
                    distribution[44] = peakHeight;
                    distribution[46] = peakHeight;
                    distribution[48] = peakHeight;
                    distribution[50] = peakHeight;
                    distribution[52] = peakHeight;
                    distribution[54] = peakHeight;
                    distribution[56] = peakHeight;
                    distribution[58] = finalPeak;
                    break;
            }
            return distribution;
        }
    }
}
